#################################### Settings ###################################
# Add here the extra packages server-side code needs
SERVER_PACKAGE   := 

# Add here the extra packages client-side code needs
CLIENT_PACKAGE   :=

# Set variables path. It has to be consistent with your configuration file.
SERVER_DIR       := _server
CLIENT_DIR       := _client
DEP_DIR          := _dep
LOCAL_DIR        := local
STATIC_DIR       := ${LOCAL_DIR}/static
VAR_DIR          := ${LOCAL_DIR}/var
DATA_DIR         := ${LOCAL_DIR}/data
LOG_DIR          := ${VAR_DIR}/log
RUN_DIR          := ${VAR_DIR}/run
OCS_COM          := ocs_com
PORT             := 8080

# Uncomment to use native-code. Remember to use ocsigenserver.opt.
# OPT		 := true

# Uncomment to use MaCaQue. Check also the configuration file.
# SERVER_PACKAGE   += macaque.syntax

# Uncomment if you use client code
CLIENT           := true
#
# # Uncomment to use OClosure.
# # CLIENT_PACKAGE   += oclosure
# # OCLOSURE         := true

include Makefile.common
